apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-scheduler

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: network-scheduler
subjects:
  - kind: ServiceAccount
    name: network-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
