apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-scheduler
  labels:
    app: network-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-scheduler
  template:
    metadata:
      name: network-scheduler
      labels:
        app: network-scheduler
    spec:
      serviceAccountName: network-scheduler
      enableServiceLinks: false
      volumes:
        - name: config
          configMap:
            name: network-scheduler-config
      containers:
        - name: network-scheduler
          image: registry.cn-shenzhen.aliyuncs.com/lin2ur/k8s-network-scheduler:0.0.2
          imagePullPolicy: IfNotPresent
          args:
            - --config=/config/config.yaml
            - --profiling=false
          volumeMounts:
            - mountPath: /config
              name: config
      restartPolicy: Always